export const mappings = {
	license_fields: {
		// Personal Information
		'DCS': 'last_name',
		'DAC': 'first_name',
		'DAD': 'middle_name',
		'DCU': 'name_suffix',
	
		// Address Information
		'DAG': 'address_1',
		'DAH': 'address_2',
		'DAI': 'city',
		'DAJ': 'state',
		'DAK': 'postal_code',
	
		// License Information
		'DAQ': 'license_number',
		'DBD': 'issue_date',
		'DBA': 'expiration_date',
		'DCF': 'doc_discriminator',
		'DCK': 'inventory_control',
	
		// Physical Description
		'DBB': 'dob',
		'DBC': 'gender',
		'DAY': 'eye_color',
		'DAU': 'height',
		'DAW': 'weight',
		'DAZ': 'hair_color',
		'DCL': 'race',
	
		// Additional Information
		'DCG': 'country',
		'DCA': 'vehicle_class',
		'DCR': 'restrictions',
		'DCQ': 'endorsements',
	
		// Other possible fields
		'DAA': 'full_name',
		'DAB': 'family_name',
		'DAE': 'name_suffix',
		'DAF': 'name_prefix',
		'DDE': 'physical_description',
		'DDF': 'residence_street_address',
		'DDG': 'residence_city_state',
	},
	
	createOrEditFieldToElementMap: {
		'last_name': 'Address_LastName',
		'first_name': 'Address_FirstName',
		// 'middle_name': 'middleName',
		// 'name_suffix': 'nameSuffix',
		'address_1': 'Address_Address1',
		'address_2': 'Address_Address2',
		'city': 'Address_City',
		'state': 'Address_StateProvinceId',
		'postal_code': 'Address_ZipPostalCode',
		// 'license_number': 'licenseNumber',
		// 'issue_date': 'issueDate',
		// 'expiration_date': 'expirationDate',
		// 'doc_discriminator': 'docDiscriminator',
		// 'inventory_control': 'inventoryControl',
		// 'dob': 'dob',
		// 'gender': 'gender',
		// 'eye_color': 'eyeColor',
		// 'height': 'height',
		// 'weight': 'weight',
		// 'hair_color': 'hairColor',
		// 'race': 'race',
		'country': 'Address_CountryId',
		// 'vehicle_class': 'vehicleClass',
		// 'restrictions': 'restrictions',
		// 'endorsements': 'endorsements'
	},

	simpleCheckoutFieldToElementMap: {
		'last_name': 'PrimaryAddress_LastName',
		'first_name': 'PrimaryAddress_FirstName',
		// 'middle_name': 'middleName',
		// 'name_suffix': 'nameSuffix',
		'address_1': 'PrimaryAddress_Address1',
		'address_2': 'PrimaryAddress_Address2',
		'city': 'PrimaryAddress_City',
		'state': 'PrimaryAddress_StateProvinceId',
		'postal_code': 'PrimaryAddress_ZipPostalCode',
		'license_number': 'checkout_attribute_6',
		// 'issue_date': 'issueDate',
		// 'expiration_date': 'expirationDate',
		// 'doc_discriminator': 'docDiscriminator',
		// 'inventory_control': 'inventoryControl',
		// 'dob': 'dob',
		// 'gender': 'gender',
		// 'eye_color': 'eyeColor',
		// 'height': 'height',
		// 'weight': 'weight',
		// 'hair_color': 'hairColor',
		// 'race': 'race',
		'country': 'PrimaryAddress_CountryId',
		// 'vehicle_class': 'vehicleClass',
		// 'restrictions': 'restrictions',
		// 'endorsements': 'endorsements'
	},
	
	stateMapping: {
		// Full names to two-letter codes
		'ALABAMA': 'AL',
		'ALASKA': 'AK',
		'ARIZONA': 'AZ',
		'ARKANSAS': 'AR',
		'CALIFORNIA': 'CA',
		'COLORADO': 'CO',
		'CONNECTICUT': 'CT',
		'DELAWARE': 'DE',
		'FLORIDA': 'FL',
		'GEORGIA': 'GA',
		'HAWAII': 'HI',
		'IDAHO': 'ID',
		'ILLINOIS': 'IL',
		'INDIANA': 'IN',
		'IOWA': 'IA',
		'KANSAS': 'KS',
		'KENTUCKY': 'KY',
		'LOUISIANA': 'LA',
		'MAINE': 'ME',
		'MARYLAND': 'MD',
		'MASSACHUSETTS': 'MA',
		'MICHIGAN': 'MI',
		'MINNESOTA': 'MN',
		'MISSISSIPPI': 'MS',
		'MISSOURI': 'MO',
		'MONTANA': 'MT',
		'NEBRASKA': 'NE',
		'NEVADA': 'NV',
		'NEW HAMPSHIRE': 'NH',
		'NEW JERSEY': 'NJ',
		'NEW MEXICO': 'NM',
		'NEW YORK': 'NY',
		'NORTH CAROLINA': 'NC',
		'NORTH DAKOTA': 'ND',
		'OHIO': 'OH',
		'OKLAHOMA': 'OK',
		'OREGON': 'OR',
		'PENNSYLVANIA': 'PA',
		'RHODE ISLAND': 'RI',
		'SOUTH CAROLINA': 'SC',
		'SOUTH DAKOTA': 'SD',
		'TENNESSEE': 'TN',
		'TEXAS': 'TX',
		'UTAH': 'UT',
		'VERMONT': 'VT',
		'VIRGINIA': 'VA',
		'WASHINGTON': 'WA',
		'WEST VIRGINIA': 'WV',
		'WISCONSIN': 'WI',
		'WYOMING': 'WY',
		'DISTRICT OF COLUMBIA': 'DC',
		'AMERICAN SAMOA': 'AS',
		'GUAM': 'GU',
		'NORTHERN MARIANA ISLANDS': 'MP',
		'PUERTO RICO': 'PR',
		'US VIRGIN ISLANDS': 'VI',
	
		// Also include two-letter codes mapping to themselves
		'ALABAMA': 'AL', 'ALASKA': 'AK', 'ARIZONA': 'AZ', 'ARKANSAS': 'AR', 'CALIFORNIA': 'CA',
		'COLORADO': 'CO', 'CONNECTICUT': 'CT', 'DELAWARE': 'DE', 'FLORIDA': 'FL', 'GEORGIA': 'GA',
		'HAWAII': 'HI', 'IDAHO': 'ID', 'ILLINOIS': 'IL', 'INDIANA': 'IN', 'IOWA': 'IA',
		'KANSAS': 'KS', 'KENTUCKY': 'KY', 'LOUISIANA': 'LA', 'MAINE': 'ME', 'MARYLAND': 'MD',
		'MASSACHUSETTS': 'MA', 'MICHIGAN': 'MI', 'MINNESOTA': 'MN', 'MISSISSIPPI': 'MS', 'MISSOURI': 'MO',
		'MONTANA': 'MT', 'NEBRASKA': 'NE', 'NEVADA': 'NV', 'NEW HAMPSHIRE': 'NH', 'NEW JERSEY': 'NJ',
		'NEW MEXICO': 'NM', 'NEW YORK': 'NY', 'NORTH CAROLINA': 'NC', 'NORTH DAKOTA': 'ND', 'OHIO': 'OH',
		'OKLAHOMA': 'OK', 'OREGON': 'OR', 'PENNSYLVANIA': 'PA', 'RHODE ISLAND': 'RI', 'SOUTH CAROLINA': 'SC',
		'SOUTH DAKOTA': 'SD', 'TENNESSEE': 'TN', 'TEXAS': 'TX', 'UTAH': 'UT', 'VERMONT': 'VT',
		'VIRGINIA': 'VA', 'WASHINGTON': 'WA', 'WEST VIRGINIA': 'WV', 'WISCONSIN': 'WI', 'WYOMING': 'WY',
		'DISTRICT OF COLUMBIA': 'DC', 'AMERICAN SAMOA': 'AS', 'GUAM': 'GU', 
		'NORTHERN MARIANA ISLANDS': 'MP', 'PUERTO RICO': 'PR', 'VIRGIN ISLANDS': 'VI'
	},
	
	addressCorrections: {
		'EAV': 'AVE',
		'AV': 'AVE',
		'AVEN': 'AVE',
		'STR': 'ST',
		'STRE': 'ST',
		'STREET': 'ST',
		'DR': 'DR',
		'DRV': 'DR',
		'DRIVE': 'DR',
		'RD': 'RD',
		'ROA': 'RD',
		'ROAD': 'RD',
		'LN': 'LN',
		'LANE': 'LN',
		'CT': 'CT',
		'CRT': 'CT',
		'COURT': 'CT',
		'CIR': 'CIR',
		'CIRC': 'CIR',
		'CIRCLE': 'CIR',
		'BLVD': 'BLVD',
		'BLV': 'BLVD',
		'BOULEVARD': 'BLVD',
		'PKW': 'PKWY',
		'PKY': 'PKWY',
		'PARKWAY': 'PKWY',
		'TER': 'TER',
		'TERR': 'TER',
		'TERRACE': 'TER',
		'HWY': 'HWY',
		'WAY': 'WAY',
		'WY': 'WAY',
		'PL': 'PL',
		'PLZ': 'PLZ',
		'PLAZA': 'PLZ',
	},
	
	directionals: {
		'N': 'N',
		'NO': 'N',
		'NORTH': 'N',
		'S': 'S',
		'SO': 'S',
		'SOUTH': 'S',
		'E': 'E',
		'EA': 'E',
		'EAST': 'E',
		'W': 'W',
		'WE': 'W',
		'WEST': 'W',
		'NE': 'NE',
		'NORTHEAST': 'NE',
		'NW': 'NW',
		'NORTHWEST': 'NW',
		'SE': 'SE',
		'SOUTHEAST': 'SE',
		'SW': 'SW',
		'SOUTHWEST': 'SW'
	}
}
